version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - celulares-net
    restart: always
    environment:
      MYSQL_DATABASE: celulares_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build: .
    container_name: celulares-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/celulares_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
    networks:
      - celulares-net 

volumes:
  mysql-data:
    driver: "local"

networks:
  celulares-net:
